# Generated by Django 4.0.1 on 2022-02-01 23:07

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_post_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.expressions.Case, to='account.photo'),
        ),
    ]
